import { defineStore } from "pinia";

import preLoad from "@/utils/preLoading";

const useMainSection = defineStore("mainSection",{
  state(){
    return{
      kind1_data:[
        {
          img:require('@/static/img/video.png'),
          text:'首页',
          linkTo:'#',
          bg_color:'#ff5c7c'
        },
        {
          img:require('@/static/img/wind_machine.png'),
          text:'动态',
          linkTo:'https://t.bilibili.com/',
          bg_color: '#fcba2a'
        },
        {
          img:require('@/static/img/popular.png'),
          text:'热门',
          linkTo:'https://www.bilibili.com/v/popular/all',
          bg_color: '#ff716d'
        },
        {
          img:require('@/static/img/channel.png'),
          text:'频道',
          linkTo:'https://www.bilibili.com/v/channel',
          bg_color: '#6dc781'
        }
      ],
      kind2_data:[
        {
          text:'动画',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/douga/',
          section_data:[
            {
              text:'MAD-AMV',
              linkTo:'https://www.bilibili.com/v/douga/mad/'
            },
            {
              text:'MMD-3D',
              linkTo:'https://www.bilibili.com/v/douga/mmd/'
            },
            {
              text:'短片·手书·配音',
              linkTo:'https://www.bilibili.com/v/douga/voice/'
            },
            {
              text:'手办·模玩',
              linkTo:'https://www.bilibili.com/v/douga/garage_kit/'
            },
            {
              text:'特摄',
              linkTo:'https://www.bilibili.com/v/douga/tokusatsu/'
            },
            {
              text:'综合',
              linkTo:'https://www.bilibili.com/v/douga/other/'
            },
          ]
        },
        {
          text:'番剧',
          num:'90',
          linkTo:'https://www.bilibili.com/anime/',
          section_data:[
            {
              text:'连载动画',
              linkTo:'https://www.bilibili.com/v/anime/serial/'
            },
            {
              text:'完结动画',
              linkTo:'https://www.bilibili.com/v/anime/finish/'
            },
            {
              text:'资讯',
              linkTo:'https://www.bilibili.com/v/anime/information/'
            },
            {
              text:'官方延申',
              linkTo:'https://www.bilibili.com/v/anime/offical/'
            },
            {
              text:'新番时间表',
              linkTo:'https://www.bilibili.com/anime/timeline/'
            },
            {
              text:'番剧索引',
              linkTo:'https://www.bilibili.com/anime/index/'
            },
          ]
        },
        {
          text:'音乐',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/music/',
          section_data:[
            {
              text:'原创音乐',
              linkTo:'https://www.bilibili.com/v/music/original/'
            },
            {
              text:'翻唱',
              linkTo:'https://www.bilibili.com/v/music/cover/'
            },
            {
              text:'VOCALOID-UTAU',
              linkTo:'https://www.bilibili.com/v/music/vocaloid/'
            },
            {
              text:'电音',
              linkTo:'https://www.bilibili.com/v/music/electronic/'
            },
            {
              text:'演奏',
              linkTo:'https://www.bilibili.com/v/music/perform/'
            },
            {
              text:'MV',
              linkTo:'https://www.bilibili.com/v/music/mv/'
            },
            {
              text:'音乐现场',
              linkTo:'https://www.bilibili.com/v/music/live/'
            },
            {
              text:'音乐综合',
              linkTo:'https://www.bilibili.com/v/music/other/'
            },
            {
              text:'音频',
              linkTo:'https://www.bilibili.com/audio/home?musicType=music'
            },
            {
              text:'说唱',
              linkTo:'https://www.bilibili.com/v/rap'
            },
          ]
        },
        {
          text:'国创',
          num:'153',
          linkTo:'https://www.bilibili.com/guochuang/',
          section_data:[
            {
              text:'国产动画',
              linkTo:'https://www.bilibili.com/v/guochuang/chinese/'
            },
            {
              text:'国产原创相关',
              linkTo:'https://www.bilibili.com/v/guochuang/original/'
            },
            {
              text:'布袋戏',
              linkTo:'https://www.bilibili.com/v/guochuang/puppetry/'
            },
            {
              text:'动态漫·广播剧',
              linkTo:'https://www.bilibili.com/v/guochuang/motioncomic/'
            },
            {
              text:'资讯',
              linkTo:'https://www.bilibili.com/v/guochuang/information/'
            },
            {
              text:'新番时间表',
              linkTo:'https://www.bilibili.com/guochuang/timeline/'
            },
            {
              text:'国产动画索引',
              linkTo:'https://www.bilibili.com/guochuang/index/'
            }
          ]
        },
        {
          text:'舞蹈',
          num:'556',
          linkTo:'https://www.bilibili.com/v/dance/',
          section_data:[
            {
              text:'宅舞',
              linkTo:'https://www.bilibili.com/v/dance/otaku/'
            },
            {
              text:'街舞',
              linkTo:'https://www.bilibili.com/v/dance/hiphop/'
            },
            {
              text:'明星舞蹈',
              linkTo:'https://www.bilibili.com/v/dance/star/'
            },
            {
              text:'中国舞',
              linkTo:'https://www.bilibili.com/v/dance/china/'
            },
            {
              text:'舞蹈综合',
              linkTo:'https://www.bilibili.com/v/dance/three_d/'
            },
            {
              text:'舞蹈教程',
              linkTo:'https://www.bilibili.com/v/dance/demo/'
            },
          ]
        },
        {
          text:'游戏',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/game/',
          section_data:[
            {
              text:'单机游戏',
              linkTo:'https://www.bilibili.com/v/game/stand_alone/'
            },
            {
              text:'电子经济',
              linkTo:'https://www.bilibili.com/v/game/esports/'
            },
            {
              text:'手机游戏',
              linkTo:'https://www.bilibili.com/v/game/mobile/'
            },
            {
              text:'网络游戏',
              linkTo:'https://www.bilibili.com/v/game/online/'
            },
            {
              text:'桌游棋牌',
              linkTo:'https://www.bilibili.com/v/game/board/'
            },
            {
              text:'GMV',
              linkTo:'https://www.bilibili.com/v/game/gmv/'
            },
            {
              text:'音游',
              linkTo:'https://www.bilibili.com/v/game/music/'
            },
            {
              text:'Mugen',
              linkTo:'https://www.bilibili.com/v/game/mugen/'
            },
            {
              text:'游戏赛事',
              linkTo:'https://www.bilibili.com/v/game/match/'
            },
          ]
        },
        {
          text:'知识',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/technology/',
          section_data:[
            {
              text:'科学科普',
              linkTo:'https://www.bilibili.com/v/technology/science/'
            },
            {
              text:'社科人文',
              linkTo:'https://www.bilibili.com/v/technology/fun/'
            },
            {
              text:'财经',
              linkTo:'https://www.bilibili.com/v/technology/finance/'
            },
            {
              text:'校园学习',
              linkTo:'https://www.bilibili.com/v/technology/campus/'
            },
            {
              text:'职业职场',
              linkTo:'https://www.bilibili.com/v/technology/career/'
            },
            {
              text:'野生技术协会',
              linkTo:'https://www.bilibili.com/v/technology/wild/'
            },
          ]
        },
        {
          text:'数码',
          num:'452',
          linkTo:'https://www.bilibili.com/v/digital/',
          section_data:[
            {
              text:'手机平板',
              linkTo:'https://www.bilibili.com/v/digital/mobile/'
            },
            {
              text:'电脑装机',
              linkTo:'https://www.bilibili.com/v/digital/pc/'
            },
            {
              text:'摄影摄像',
              linkTo:'https://www.bilibili.com/v/digital/photography/'
            },
            {
              text:'影音智能',
              linkTo:'https://www.bilibili.com/v/digital/intelligence_av/'
            }
          ]
        },
        {
          text:'生活',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/life/',
          section_data:[
            {
              text:'搞笑',
              linkTo:'https://www.bilibili.com/v/life/funny/'
            },
            {
              text:'日常',
              linkTo:'https://www.bilibili.com/v/life/daily/'
            },
            {
              text:'动物圈',
              linkTo:'https://www.bilibili.com/v/life/animal/'
            },
            {
              text:'手工',
              linkTo:'https://www.bilibili.com/v/life/handmake/'
            },
            {
              text:'绘画',
              linkTo:'https://www.bilibili.com/v/life/painting/'
            },
            {
              text:'运动',
              linkTo:'https://www.bilibili.com/v/life/sports/'
            },
            {
              text:'汽车',
              linkTo:'https://www.bilibili.com/v/life/automobile/'
            },
            {
              text:'其他',
              linkTo:'https://www.bilibili.com/v/life/other/'
            }
          ]
        },
        {
          text:'鬼畜',
          num:'60',
          linkTo:'https://www.bilibili.com/v/kichiku/',
          section_data:[
            {
              text:'鬼畜调教',
              linkTo:'https://www.bilibili.com/v/kichiku/guide/'
            },
            {
              text:'音MAD',
              linkTo:'https://www.bilibili.com/v/kichiku/mad/'
            },
            {
              text:'人力VOCALOID',
              linkTo:'https://www.bilibili.com/v/kichiku/manual_vocaloid/'
            },
            {
              text:'鬼畜剧场',
              linkTo:'https://www.bilibili.com/v/kichiku/theatre/'
            },
            {
              text:'教程演示',
              linkTo:'https://www.bilibili.com/v/kichiku/course/'
            },
            {
              text:'综合',
              linkTo:'https://www.bilibili.com/v/douga/other/'
            },
          ]
        },
        {
          text:'时尚',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/fashion/',
          section_data:[
            {
              text:'美妆',
              linkTo:'https://www.bilibili.com/v/fashion/makeup/'
            },
            {
              text:'服饰',
              linkTo:'https://www.bilibili.com/v/fashion/clothing/'
            },
            {
              text:'健身',
              linkTo:'https://www.bilibili.com/v/fashion/aerobics/'
            },
            {
              text:'T台',
              linkTo:'https://www.bilibili.com/v/fashion/catwalk/'
            },
            {
              text:'风尚标',
              linkTo:'https://www.bilibili.com/v/fashion/trends/'
            }
          ]
        },
        {
          text:'资讯',
          num:'119',
          linkTo:'https://www.bilibili.com/v/information/',
          section_data:[
            {
              text:'热点',
              linkTo:'https://www.bilibili.com/v/information/hotspot/'
            },
            {
              text:'环球',
              linkTo:'https://www.bilibili.com/v/information/global/'
            },
            {
              text:'社会',
              linkTo:'https://www.bilibili.com/v/information/social/'
            },
            {
              text:'综合',
              linkTo:'https://www.bilibili.com/v/information/multiple/'
            }
          ]
        },
        {
          text:'娱乐',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/ent/',
          section_data:[
            {
              text:'综艺',
              linkTo:'https://www.bilibili.com/v/ent/variety/'
            },
            {
              text:'明显',
              linkTo:'https://www.bilibili.com/v/ent/star/'
            }
          ]
        },
        {
          text:'影视',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/cinephile/',
          section_data:[
            {
              text:'影视杂谈',
              linkTo:'https://www.bilibili.com/v/cinephile/cinecism/'
            },
            {
              text:'影视剪辑',
              linkTo:'https://www.bilibili.com/v/cinephile/montage/'
            },
            {
              text:'短片',
              linkTo:'https://www.bilibili.com/v/cinephile/shortfilm/'
            },
            {
              text:'预告·咨询',
              linkTo:'https://www.bilibili.com/v/cinephile/trailer_info/'
            }
          ]
        },
        {
          text:'放映厅',
          num:'18',
          linkTo:'https://www.bilibili.com/cinema/',
          section_data:[
            {
              text:'纪录片',
              linkTo:'https://www.bilibili.com/documentary/'
            },
            {
              text:'电影',
              linkTo:'https://www.bilibili.com/movie/'
            },
            {
              text:'电视剧',
              linkTo:'https://www.bilibili.com/tv/'
            }
          ]
        },
        {
          text:'搞笑',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/life/funny',
          section_data:[]
        },
        {
          text:'动物圈',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/life/animal',
          section_data:[]
        },
        {
          text:'美食',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/food',
          section_data:[]
        },
        {
          text:'单机游戏',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/game/stand_alone',
          section_data:[]
        },
        {
          text:'VLOG',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/food',
          section_data:[]
        }
      ],
      more_navigation:{
        text:'更多',
        num:'^',
        linkTo:'#',
        section_data:[
          {
            text:'搞笑',
            linkTo:'https://www.bilibili.com/v/life/funny',
          },
          {
            text:'动物圈',
            linkTo:'https://www.bilibili.com/v/life/animal',
          },
          {
            text:'美食',
            linkTo:'https://www.bilibili.com/v/food',
          },
          {
            text:'单机游戏',
            linkTo:'https://www.bilibili.com/v/game/stand_alone',
          },
          {
            text:'VLOG',
            linkTo:'https://www.bilibili.com/v/food',
          }
        ]
      },
      kind3_data:[
        {
          img:require('@/static/img/special_column.png'),
          linkTo:'https://www.bilibili.com/read/home',
          text:'专栏'
        },
        {
          img:require('@/static/img/activity.png'),
          linkTo:'https://www.bilibili.com/blackboard/x/act_list',
          text:'活动'
        },
        {
          img:require('@/static/img/class.png'),
          linkTo:'https://www.bilibili.com/cheese/',
          text:'课堂'
        },
        {
          img:require('@/static/img/streaming.png'),
          linkTo:'https://live.bilibili.com/',
          text:'直播'
        },
        {
          img:require('@/static/img/room.png'),
          linkTo:'https://www.bilibili.com/blackroom/',
          text:'小黑屋'
        },
        {
          img:require('@/static/img/music_plus.png'),
          linkTo:'https://www.bilibili.com/v/musicplus/',
          text:'音乐PLUS'
        }
      ],
      flow_img_1_data:[
        {
          img:require('@/static/img/flow_img_1.jpg'),
          linkTo:'https://live.bilibili.com/5086',
          text:'这次占领最前排',
          is_advertised:false
        },
        {
          img:require('@/static/img/flow_img_2.jpg'),
          linkTo:'https://cm.bilibili.com/cm/api/fees/pc/sync/v2?msg=a%7C3199%2Cb%7Cbilibili%2Cc%7C1%2Cd%7C1%2Ce%7CCAAQABiA4LWBt6zCkgYgACgAMB04%2FxhCHzE2MDg5NTA3NzIwMjZxMTcyYTIzYTY4YTUxcTUzMDJIuuLB5%2BkuUgbmoKrmtLJaBua5luWNl2IG5Lit5Zu9aGRwAXiAgICAkBKAAQCIAYF8kgENMTE5LjM5LjEzMy43OJoB9AthbGw6Y3BjX2Nyb3dkX3RhcmdldCxjcGNUYWdGaWx0ZXI6dW5kZWZpbmVkLHBwY3RyOmhtX2NvZXVzLG5vX2FkOnVuZGVmaW5lZCxicnVzaF9kdXA6ZGVmYXVsdCxmZF9wY3RyOmRkX3YzX2VjcG1fdjEwLGN2cl9wOmJhc2VfY29ldXMsZGN2cmY6Y2x1ZV9jb3N0LGN2cl9mOmRubjIsY3BhOndlaWdodCxVVjp1bmRlZmluZWQsaGFzaFVWOkIscHY6dW5kZWZpbmVkLGZkX3JhbmRvbTpkZWZhdWx0LGZsb3dfcmF0aW86cjMsZG1wX2FnZTpkbXAsbkZlZEJhY2s6bG9vc2UscWlmZWk6dGhyZXNfZTIsZmlsdGVyT3B0Om9wZW4saW5uZXJfZW5oYW5jZTpjbG9zZSxSUzp0NTAwLGRwczpjb25zdGFudCxvcGVuZmx5bmV3Om9wZW4sZmx5X3BjdnI6dGhyZXNfZTIsZmx5X29jcG06YWExLGZseV9jcGE6cHpxLGg1X3Y6TkEscEVOOlBSLHNGQnJ1OjIsZmRTQjpkZWZhdWx0LHRpbWVGcmVxOmRlZmF1bHQsY3VjbzoxMjAscHVjbzo0MCx1dlRlc3Q6YTEsb2NwbVRocjpkZWZhdWx0LGRvd25ncmFkZTpub192MixkQWR4OmRlZmF1bHQsdXNlR3JwYzpmYWxzZSxtZXJjeVBiOmFsbCxmcmVTOmxvd2NyZWF0aXZlLGNvYXJzZTpjb2Fyc2VfY3ZyX2RpcmVjdGNyb3NzLHBwQjpzaG93LGNyb3dkUzpDLGNvbGRSOmNvbnN0YW50LGZseV90cnVucDptb3V0LHNtYXJ0YmlkOmRlZmF1bHQsYWxsRmxvdzpkZWZhdWx0LGNyb3dkc0xvZzplbmFibGUsZWNwbTpkZWZhdWx0LHBjdHJfY3BtOmNwbSxwY3RyX2NvbnN0YW50OmRmdCxkeW5hbWljX2Zsb3dfY29udHJvbDpzcGxpdCB0aGUgZmxvdyBieSBtaWQsb3V0ZXJCZWF0SW5uZXI6ZGVmYXVsdCxvdXRlclF1aXQ6ZGVmYXVsdCxjb2xkX2Jvb3RfZXhwOmRlZmF1bHQsbnRoX2JydXNoX2V2ZW50OmRlZmF1bHQsbG93X3F0eV9jcmVhdGl2ZTpsb3dfcXR5LGVuYWJsZVBhcmFsbGVsOnRydWUsbGltaXRfYWR4OmRlZmF1bHQsc29ydEFkeDpzb3J0QWR4X3RydWUsb2NwbVR3b1N0YWdlUGN2clRocmVzaG9sZEV4cDpkZWZhdWx0LHBwU0I6b3BlbixjcmVhdGl2ZUZyZXFGaWx0ZXI6Y2x1c3RlcixibG9ja0NvbW1lbnQ6ZGVmYXVsdCxvY3BtX3N1cHBvcnQ6b3BlbkNvbnRlbnRVcENvbmZpZ0xhbWJkYSxmbHlfY3BtX2VjcG06b3BlbixtZXQ6MzM1LGJ1ZGdldF9zbW9vdGhfbmV3OmNvbnN0YW50LHBjRXhwZXJpbWVudDpwY0V4cGVyaW1lbnRFbmFibGUscGNwY3ZyOmJhc2UsZW5hYmxlQXBwU3RvcmVQcmVsb2FkOmVuYWJsZSxjYXNzaW5pRXhwOm9wZW4sQ3JlYXRpdmVRdWFsaXR5OmJhc2UscnRhRXhwOm9wZW4sZ2lmX2V4cDpiYXNlLGlubGluZUV4cDpwbGFuQixwcm9ncmFtQ3JlYXRpdmU6cmFuZG9tLG9wZW5CdXNpbmVzc1VwQ3BjOm9wZW4sYnJhbmRJbmZvRXhwOmRlZmF1bHQsZHBhMlN0cmF0ZWd5OmRlZmF1bHQsYnJhbmRDbG9zZVByU2hvd0FkOmZhbHNlLGRwYTI6Y2xvc2VDcm93ZCxyZXNlcnZlX3ByaWNlOmV4dHJhLGJnVGFnOm5vbmUsdXNlQXM6Y2xvc2UsYnV2aWREbXBVc2VyUHJvZmlsZUV4cDpjbG9zZSxhcmVhUmVwbGFjZTpkZWZhdWx0LHBsYXRmb3JtOmRlZmF1bHSgAQCoAQCyASDlmBtJUsn92OUzckQarGZShF3B%2FIMqYlyIpAxSJ6se17oBN2h0dHBzOi8vd3d3LmJpbGliaWxpLmNvbS9ibGFja2JvYXJkL2FjdGl2aXR5LUJPU0NILmh0bWzCAQDSAQDYAZEB4AEA6AEA8AEA%2BAEAgAIAiAIAuAIAwAIAyAIA0AIA2AIA6gIA8AK4zwn4AgCIAwGSAwCoAwCwAwC4AwDCAwDIA5%2BNBtIDQXsiMSI6IjQ0Mjc3MDQ2MTA1NDMwMDE2MCIsIjIiOiIyOSIsIjQiOiI2MyIsIjUiOiIxMDciLCI2IjoiMjlfMCJ94AMA6AMC8AMA%2BgMFb3RoZXKCBAludWxsOm51bGyIBACQBACYBACgBACqBAQIABAEsAQA%2Cf%7Cclick_sync_3%2Cg%7C1%2Ch%7C2%2Ci%7C%2Cj%7C%2Ck%7C1608955680271%2Cl%7C%2Cm%7C1608950772553%2Cn%7C1%2Co%7C&ts=1608955680271',
          text:'博世家电10万圣诞豪礼',
          is_advertised:true
        },
        {
          img:require('@/static/img/default_img_big.jpg'),
          linkTo:'https://cm.bilibili.com/cm/api/fees/pc/sync/v2?msg=a%7C3200%2Cb%7Cbilibili%2Cc%7C1%2Cd%7C1%2Ce%7CCAAQABiA4I7XmJ39lgYgACgAMCQ4gBlCHzE2MDg5NTA3NzIwMjZxMTcyYTIzYTY4YTUxcTUzMDJIuuLB5%2BkuUgbmoKrmtLJaBua5luWNl2IG5Lit5Zu9aGRwAXiAgICAkBKAAQCIAbl4kgENMTE5LjM5LjEzMy43OJoB9AthbGw6Y3BjX2Nyb3dkX3RhcmdldCxjcGNUYWdGaWx0ZXI6dW5kZWZpbmVkLHBwY3RyOmhtX2NvZXVzLG5vX2FkOnVuZGVmaW5lZCxicnVzaF9kdXA6ZGVmYXVsdCxmZF9wY3RyOmRkX3YzX2VjcG1fdjEwLGN2cl9wOmJhc2VfY29ldXMsZGN2cmY6Y2x1ZV9jb3N0LGN2cl9mOmRubjIsY3BhOndlaWdodCxVVjp1bmRlZmluZWQsaGFzaFVWOkIscHY6dW5kZWZpbmVkLGZkX3JhbmRvbTpkZWZhdWx0LGZsb3dfcmF0aW86cjMsZG1wX2FnZTpkbXAsbkZlZEJhY2s6bG9vc2UscWlmZWk6dGhyZXNfZTIsZmlsdGVyT3B0Om9wZW4saW5uZXJfZW5oYW5jZTpjbG9zZSxSUzp0NTAwLGRwczpjb25zdGFudCxvcGVuZmx5bmV3Om9wZW4sZmx5X3BjdnI6dGhyZXNfZTIsZmx5X29jcG06YWExLGZseV9jcGE6cHpxLGg1X3Y6TkEscEVOOlBSLHNGQnJ1OjIsZmRTQjpkZWZhdWx0LHRpbWVGcmVxOmRlZmF1bHQsY3VjbzoxMjAscHVjbzo0MCx1dlRlc3Q6YTEsb2NwbVRocjpkZWZhdWx0LGRvd25ncmFkZTpub192MixkQWR4OmRlZmF1bHQsdXNlR3JwYzpmYWxzZSxtZXJjeVBiOmFsbCxmcmVTOmxvd2NyZWF0aXZlLGNvYXJzZTpjb2Fyc2VfY3ZyX2RpcmVjdGNyb3NzLHBwQjpzaG93LGNyb3dkUzpDLGNvbGRSOmNvbnN0YW50LGZseV90cnVucDptb3V0LHNtYXJ0YmlkOmRlZmF1bHQsYWxsRmxvdzpkZWZhdWx0LGNyb3dkc0xvZzplbmFibGUsZWNwbTpkZWZhdWx0LHBjdHJfY3BtOmNwbSxwY3RyX2NvbnN0YW50OmRmdCxkeW5hbWljX2Zsb3dfY29udHJvbDpzcGxpdCB0aGUgZmxvdyBieSBtaWQsb3V0ZXJCZWF0SW5uZXI6ZGVmYXVsdCxvdXRlclF1aXQ6ZGVmYXVsdCxjb2xkX2Jvb3RfZXhwOmRlZmF1bHQsbnRoX2JydXNoX2V2ZW50OmRlZmF1bHQsbG93X3F0eV9jcmVhdGl2ZTpsb3dfcXR5LGVuYWJsZVBhcmFsbGVsOnRydWUsbGltaXRfYWR4OmRlZmF1bHQsc29ydEFkeDpzb3J0QWR4X3RydWUsb2NwbVR3b1N0YWdlUGN2clRocmVzaG9sZEV4cDpkZWZhdWx0LHBwU0I6b3BlbixjcmVhdGl2ZUZyZXFGaWx0ZXI6Y2x1c3RlcixibG9ja0NvbW1lbnQ6ZGVmYXVsdCxvY3BtX3N1cHBvcnQ6b3BlbkNvbnRlbnRVcENvbmZpZ0xhbWJkYSxmbHlfY3BtX2VjcG06b3BlbixtZXQ6MzM1LGJ1ZGdldF9zbW9vdGhfbmV3OmNvbnN0YW50LHBjRXhwZXJpbWVudDpwY0V4cGVyaW1lbnRFbmFibGUscGNwY3ZyOmJhc2UsZW5hYmxlQXBwU3RvcmVQcmVsb2FkOmVuYWJsZSxjYXNzaW5pRXhwOm9wZW4sQ3JlYXRpdmVRdWFsaXR5OmJhc2UscnRhRXhwOm9wZW4sZ2lmX2V4cDpiYXNlLGlubGluZUV4cDpwbGFuQixwcm9ncmFtQ3JlYXRpdmU6cmFuZG9tLG9wZW5CdXNpbmVzc1VwQ3BjOm9wZW4sYnJhbmRJbmZvRXhwOmRlZmF1bHQsZHBhMlN0cmF0ZWd5OmRlZmF1bHQsYnJhbmRDbG9zZVByU2hvd0FkOmZhbHNlLGRwYTI6Y2xvc2VDcm93ZCxyZXNlcnZlX3ByaWNlOmV4dHJhLGJnVGFnOm5vbmUsdXNlQXM6Y2xvc2UsYnV2aWREbXBVc2VyUHJvZmlsZUV4cDpjbG9zZSxhcmVhUmVwbGFjZTpkZWZhdWx0LHBsYXRmb3JtOmRlZmF1bHSgAQCoAQCyASDl9z%2FqzWwCGwCAYd2BX3%2FXNRVD6Y72xywBk0dCvI7sWroB1QFodHRwczovL2FkLWJpbGktZGF0YS5iaWxpZ2FtZS5jb20vdjIvYXBpL2NsaWNrL3BjX2JpbGk%2FbWlkPV9fTUlEX18maXA9MTE5LjM5LjEzMy43OCZyZXF1ZXN0X2lkPTE2MDg5NTA3NzIwMjZxMTcyYTIzYTY4YTUxcTUzMDImdHM9X19UU19fJnVhPV9fVUFfXyZhZF9jaGFubmVsX2lkPTMmYWRfZj1kMzAzZWI0YTRiZGI0MjIwYmE0ODA4OThlY2Y1YmUwMiZnYW1lX2lkPTQ1MjTCAQDSAQDYAZEB4AEA6AEA8AEA%2BAEAgAIAiAIAuAIAwAIAyAIA0AIA2AIA6gIA8ALKvAn4AgCIAwGSAwCoAwCwAwC4AwDCAwDIA5%2BNBtIDQXsiMSI6IjQ0NTI4MTIyMjA3NDI4MTk4NCIsIjIiOiIzNiIsIjQiOiI5MCIsIjUiOiIyOTIiLCI2IjoiMzZfMCJ94AMA6AMC8AMA%2BgMFb3RoZXKCBAludWxsOm51bGyIBACQBACYBACgBACqBAQIABAEsAQA%2Cf%7Cclick_sync_3%2Cg%7C1%2Ch%7C3%2Ci%7C%2Cj%7C%2Ck%7C1608955757065%2Cl%7C%2Cm%7C1608950772553%2Cn%7C1%2Co%7C&ts=1608955757065',
          text:'百万预约福利即将解锁',
          is_advertised:true
        },
        {
          img:require('@/static/img/default_img_big.jpg'),
          linkTo:'https://www.bilibili.com/2020/',
          text:'12月30日跨晚解密揭秘！',
          is_advertised:false
        },
        {
          img:require('@/static/img/default_img_big.jpg'),
          linkTo:'https://www.bilibili.com/bangumi/play/ss34792',
          text:'年度最不容错过的欧美虐恋剧',
          is_advertised:false
        },
        {
          img:require('@/static/img/default_img_big.jpg'),
          linkTo:'https://live.bilibili.com/5086',
          text:'这次占领最前排',
          is_advertised:false
        },
      ],
      flow_img_2_data:[
        {
          img:require('@/static/img/flow_img2_1.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1Xy4y1m7eH',
          head:'【原神】年度最强COS短片,跨越尘世的冒险之旅',
          up_name:'萧影殿下',
          num:691200
        },
        {
          img:require('@/static/img/flow_img2_2.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1hA411p74R',
          head:'我给up主们喂饭的日子',
          up_name:'幾加乘',
          num:16100
        },
        {
          img:require('@/static/img/flow_img2_3.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1Wy4y1e71X',
          head:'【FGO2.5.1杂谈】私欲的英雄与击坠神明之人',
          up_name:'削人棍专用BGM',
          num:86100
        },
        {
          img:require('@/static/img/flow_img2_4.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1ZA411s7Tx',
          head:'【仿原神/实时渲染】啊，这光！啊，这水！芭芭拉的Solo☆MV (?)【2D卡通渲染】',
          up_name:'NoiR_CCC',
          num:72100
        },
        {
          img:require('@/static/img/flow_img2_5.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1BT4y1K7aT',
          head:'在故宫拍照都能毁容！医院急症室真的有这么多奇葩吗？',
          up_name:'整形医生肖一丁',
          num:106100
        },
        {
          img:require('@/static/img/flow_img2_6.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1Cv41147KH',
          head:'【爆肝650+张】流汗吧！适格女武神！',
          up_name:'帷幕VMovie',
          num:88100
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1YX4y1T7ad',
          head:'7周年記念【小巫】103曲宅舞连跳 愿舞区越来越好♥踊ってみた',
          up_name:'小巫酱w',
          num:38100
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1T64y1Z7T7',
          head:'圣诞节，她回来了，然后...',
          up_name:'大大大灯泡',
          num:289000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV15h411f7vL',
          head:'【GTA5/侠盗猎车手5】专题(下): 故事永不完结，神作永不褪色 Grand Theft Auto 2013',
          up_name:'Leya蕾雅',
          num:76000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV17i4y1w7xF',
          head:'流泪的夜莺（原创曲）',
          up_name:'hanser',
          num:102000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1fi4y1c7wh',
          head:'【Hiiro】完全放棄宣言',
          up_name:'HiiroVTuber',
          num:75000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1bz4y1r7yt',
          head:'赛博朋克2077里的飞船能不能坐？自己创造飞行载具！实现空中跑酷。',
          up_name:'逗川kshadow',
          num:185000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1Wo4y1Z7bP',
          head:'【小林未郁】日语填词，翻唱周深，你从未听过的船新版本！#能解答一切的答案#',
          up_name:'小林未郁miccabose',
          num:109000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1az4y1r7TQ',
          head:'咒术人私下私密视频流出',
          up_name:'糖森君',
          num:21000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1tK4y1V7hf',
          head:'【1900】要凉？大臣竟上了暗杀名单《是，大臣》（10/S2E3）',
          up_name:'1900影剧室',
          num:92000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1XK411u7H8',
          head:'铁打的杰斯顿，打铁的塞雷娅【方舟沙雕新闻】#15',
          up_name:'魏晋南北',
          num:214000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV15K411g7Bv',
          head:'【泛式】奶爆新番！一月最值得期待的10部动画！霸权竟是他自己？',
          up_name:'泛式',
          num:488000
        },
        {
          img:require('@/static/img/default_img_middle.jpg'),
          linkTo:'https://www.bilibili.com/video/BV1vy4y1i7MD',
          head:'惊了！语文课文中竟然有这种烧脑剧情',
          up_name:'不正经老丝',
          num:683000
        }
      ],
      popularize_data:{
        text:'推广',
        head_img:require('@/static/img/ad_section.png'),
        head_linkTo:'https://www.bilibili.com/v/douga',
        body:[
          {
            img:require('@/static/img/ad_2.jpg'),
            linkTo:'https://cm.bilibili.com/cm/api/fees/pc/sync/v2?msg=a%7C35%2Cb%7Cbilibili%2Cc%7C1%2Cd%7C1%2Ce%7CCKXiLRDF%2Bo8BGIm29CkgxAQoATDzhAE4I0IfMTYwODk1MDc3MjAyNnExNzJhMjNhNjhhNTFxNTMwMki64sHn6S5SBuagqua0sloG5rmW5Y2XYgbkuK3lm71oZHABeICAgICQGIABA4gBAJIBDTExOS4zOS4xMzMuNziaAQCgAcQEqAEJsgEg6WVTqt37StAUWhrT9jik8yoRKzU8f0MQjL7vU%2Bb4jgq6AZ0CaHR0cHM6Ly9tei50YW56aG91ZWR1LmNvbS8%2Fcz02ZGQ1OGYyOTdhNjMwMDQ1JnRyYWNrX2lkPVNJUzhEU2Jiam1jZEtZZ2ZKX3g0WkV1UGNwaExNeVBObF9Ua0I1bjNFbVkwcVJkOGhUUXdYbzJyQS1QYUk0SWxhbzZ4bGFRLVA1YTZTN0sycmNYS1dXNDE4WHhWQmhNandxTmhpamt4VXk1NWJiSUUwQW9kZU40MF9oNUpCUVl1Nk5Qd1BOdDhBdnc1OTF4NXZTbDdyVU05TXlqdlJaNjRhN0kyNmJneFk5YyUzRCZjcmlkPTg3ODkwNjk3JmlkZmE9X19JREZBX18maW1laT1fX0lNRUlfXyZvYWlkPV9fT0FJRF9fwgGVATI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzI4XzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQyXzQy0gEA2AHBAeABoI0G6AGQTvABAPgBhwSAAgKIAgCSAvsCMjMxMjQwNV8xNjA4NzMyNzQxLDIxMjE2MjlfMTYwODczMjc0MSwyMzM2NjcxXzE2MDg3MzI3NDEsMjM2MDI3Nl8xNjA4NzMyNzQxLDE4MTc2MjZfMTYwODczMjc3NywyMDMzNDIxXzE2MDg3MzI4MDgsMjE5MTA5MF8xNjA4NzgxMTg0LDIxNjQ4NTNfMTYwODc4MTE4NCwyMzk1ODAzXzE2MDg3ODExODQsMjM1OTcwMl8xNjA4Nzg3NzE4LDIzOTU0OTJfMTYwODc4NzcxOCwyMTY0ODUzXzE2MDg3ODc3MTgsMjM2Mjk3N18xNjA4ODE3MDc1LDIxNjQ4NTNfMTYwODgxNzA3NSwyMzYzNTcyXzE2MDg4MTcwODAsMjMxMjUyN18xNjA4ODE3MDgwLDIzMzUzNTBfMTYwODg2NDU4OSwyMzEwNDU0XzE2MDg4NjQ1ODksMjM1NTc4NV8xNjA4ODY0NTg5LDIwMzM0MjFfMTYwODg4ODMzNpgCkL8EoAIqqALCVLACBbgCAMACgKjWuQfIAgDQAgDYAgDqAgDwAgD4AqkEiAMBkgMAqAMAsAMAuAMAwgMAyAOfjQbSAzp7IjEiOiI4Nzg5MDY5NyIsIjIiOiIxNzAxMSIsIjQiOiIzOCIsIjUiOiI0NiIsIjYiOiIzXzU1MyJ94AMC6AMC8AMA%2BgMFb3RoZXKCBAludWxsOm51bGyIBMQEkAQAmAQAoAQiqgQHCJyFhAEQBKoEBgihnGAQAbAEAA%3D%3D%2Cf%7Cclick_sync_3%2Cg%7C1%2Ch%7C1%2Ci%7C%2Cj%7C%2Ck%7C1608950773048%2Cl%7C%2Cm%7C1608950772553%2Cn%7C1%2Co%7C&ts=1608950773048',
            text:'每天特效一小时，挑战接单买AJ！'
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1PZ4y1374i',
            img:require('@/static/img/video_1.jpg'),
            num:13200,
            like:7300,
            time:'10.25',
            text:'零下40度过圣诞？我带着大家的愿望去中国最北站！',
            bk_img:require('@/static/img/video_animated_1.jpg'),
            up_name:'小软iris',
            up_linkTo:'https://space.bilibili.com/692988/',
            img_num:74
          },
          {
            img:require('@/static/img/ad_3.jpg'),
            linkTo:'https://cm.bilibili.com/cm/api/fees/pc/sync/v2?msg=a%7C37%2Cb%7Cbilibili%2Cc%7C1%2Cd%7C1%2Ce%7CCP76KRDPgokBGJ6qpCkg5wEoATCbgRY4JUIfMTYwODk1MDc3MjAyNnExNzJhMjNhNjhhNTFxNTMwMki64sHn6S5SBuagqua0sloG5rmW5Y2XYgbkuK3lm71oZHABeICAgICQGIABA4gBAJIBDTExOS4zOS4xMzMuNziaAQCgAecBqAEVsgEgVtsMGOFGTbcyin3bx55h1z3T08%2Fq93aoImrW6aMn%2BaS6AUhodHRwOi8vc2QuemNlZHVzdHVkeS5jb20veWcvYmlsaWJpbGkvOTA3My9wYy9xZy8wNS04L2luZGV4Lmh0bWwjMjAxMTI1LTHCAZUBMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDLSAQDYAcEB4AHgw54E6AHgw54E8AEA%2BAG%2FAYACAogCAJIC%2BwIyMzEyNDA1XzE2MDg3MzI3NDEsMjEyMTYyOV8xNjA4NzMyNzQxLDIzMzY2NzFfMTYwODczMjc0MSwyMzYwMjc2XzE2MDg3MzI3NDEsMTgxNzYyNl8xNjA4NzMyNzc3LDIwMzM0MjFfMTYwODczMjgwOCwyMTkxMDkwXzE2MDg3ODExODQsMjE2NDg1M18xNjA4NzgxMTg0LDIzOTU4MDNfMTYwODc4MTE4NCwyMzU5NzAyXzE2MDg3ODc3MTgsMjM5NTQ5Ml8xNjA4Nzg3NzE4LDIxNjQ4NTNfMTYwODc4NzcxOCwyMzYyOTc3XzE2MDg4MTcwNzUsMjE2NDg1M18xNjA4ODE3MDc1LDIzNjM1NzJfMTYwODgxNzA4MCwyMzEyNTI3XzE2MDg4MTcwODAsMjMzNTM1MF8xNjA4ODY0NTg5LDIzMTA0NTRfMTYwODg2NDU4OSwyMzU1Nzg1XzE2MDg4NjQ1ODksMjAzMzQyMV8xNjA4ODg4MzM2mAKchY8XoAKmiQSoAoqrCrAC%2BwG4AgDAAoDiCcgCANACANgCAOoCAPACAPgCAIgDAZIDAKgDALADALgDAMIDAMgDn40G0gM8eyIxIjoiODY1Nzg0NjIiLCIyIjoiMzYwNjAzIiwiNCI6IjM4IiwiNSI6IjQ3IiwiNiI6IjI2NzFfMCJ94AMC6AMC8AMA%2BgMFb3RoZXKCBAludWxsOm51bGyIBOcBkAQAmAQAoAQiqgQGCKPXfRAEqgQGCI%2BRfxABsAQA%2Cf%7Cclick_sync_3%2Cg%7C1%2Ch%7C3%2Ci%7C%2Cj%7C%2Ck%7C1608950773050%2Cl%7C%2Cm%7C1608950772553%2Cn%7C1%2Co%7C&ts=1608950773050',
            text:'每天建模一小时，挑战外包赚钱！'
          },
          {
            linkTo:'https://www.bilibili.com/video/BV17y4y1e71S',
            img:require('@/static/img/video_2.jpg'),
            num:1421200,
            like:113000,
            time:'03.11',
            text:'【全明星】欧若拉 - 这首回到过去的歌你听过吗？',
            bk_img:require('@/static/img/video_animated_2.jpg'),
            up_name:'秋名山上的486',
            up_linkTo:'https://space.bilibili.com/101376123/',
            img_num: 35
          }
        ],
        advertised_img:require('@/static/img/ad_1.jpg'),
        advertised_linkTo:'https://www.bilibili.com/read/cv8862904'
      },
      advertisement_data:{
        linkTo:'https://cm.bilibili.com/cm/api/fees/pc/sync/v2?msg=a%7C41%2Cb%7Cbilibili%2Cc%7C1%2Cd%7C1%2Ce%7CCLSYLxCZnZIBGIvahyoguQMoATDgnxc4KUIfMTYwODk1MDc3MjAyNnExNzJhMjNhNjhhNTFxNTMwMki64sHn6S5SBuagqua0sloG5rmW5Y2XYgbkuK3lm71oZHABeICAgICQDYABA4gBAJIBDTExOS4zOS4xMzMuNziaAQCgAbkDqAEUsgEgO941WR07OFw6od%2FWnPpibMq1zJuYWolytNRStWClPlm6Af4BaHR0cDovL212cC5jZ2RldXZpcC5jb20veWcvYmlsaWJpbGkva3gwNC9wYy9xZy8wMS0xMS9pbmRleC5odG1sIzEyMjMtMT90cmFja19pZD1TSVM4RFNiYmptY2RLWWdmSl94NFpFdVBjcGhMTXlQTmxfVGtCNW4zRW1ZMHFSZDhoVFF3WG8yckEtUGFJNElsYW82eGxhUS1QNWE2UzdLMnJjWEtXVzQxOFh4VkJoTWp3cU5oaWpreFV5NkdPVmpraElqRlhjRmpKeU9pZTBOUGZCMG9ibWY2QTVBbDNPQWFIRDRMTHRBRjA2TmZZVkI1bk9XcHEyRFRyVEUlM0TCAZUBMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfMjhfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDJfNDLSAQDYAWngAaDCHugB4LUF8AEA%2BAG2A4ACAogCAJIC%2BwIyMzEyNDA1XzE2MDg3MzI3NDEsMjEyMTYyOV8xNjA4NzMyNzQxLDIzMzY2NzFfMTYwODczMjc0MSwyMzYwMjc2XzE2MDg3MzI3NDEsMTgxNzYyNl8xNjA4NzMyNzc3LDIwMzM0MjFfMTYwODczMjgwOCwyMTkxMDkwXzE2MDg3ODExODQsMjE2NDg1M18xNjA4NzgxMTg0LDIzOTU4MDNfMTYwODc4MTE4NCwyMzU5NzAyXzE2MDg3ODc3MTgsMjM5NTQ5Ml8xNjA4Nzg3NzE4LDIxNjQ4NTNfMTYwODc4NzcxOCwyMzYyOTc3XzE2MDg4MTcwNzUsMjE2NDg1M18xNjA4ODE3MDc1LDIzNjM1NzJfMTYwODgxNzA4MCwyMzEyNTI3XzE2MDg4MTcwODAsMjMzNTM1MF8xNjA4ODY0NTg5LDIzMTA0NTRfMTYwODg2NDU4OSwyMzU1Nzg1XzE2MDg4NjQ1ODksMjAzMzQyMV8xNjA4ODg4MzM2mAKmggqgArsBqAL57wGwAiS4AgDAAszaBsgC8AHQAgDYAgDqAgDwAgD4AgCIAwGSAwCoAwCwAwC4AwDCAwDIA5%2BNBtIDPHsiMSI6Ijg4MjA2NjAzIiwiMiI6IjM4MDg5NiIsIjQiOiIzOCIsIjUiOiI0NyIsIjYiOiIyNzU0XzAifeADAugDAvADAPoDBW90aGVyggQJbnVsbDpudWxsiAS5A5AEAJgEAKAEGqoEBAh3EASqBAcIne2EARABsAQA%2Cf%7Cclick_sync_3%2Cg%7C1%2Ch%7C1%2Ci%7C%2Cj%7C%2Ck%7C1608950773173%2Cl%7C%2Cm%7C1608950772553%2Cn%7C1%2Co%7C&ts=1608950773173',
        img:require('@/static/img/guang_gao1.jpg')
      },
      video_section_1_data:{
        head_img:require('@/static/img/donghua_head.png'),
        head_text:'动画',
        head_text_linkTo:'https://www.bilibili.com/v/douga',
        more_linkTo:'https://www.bilibili.com/v/douga',
        video_item:[
          {
            linkTo:'https://www.bilibili.com/video/BV1GA411s7D5',
            img:require('@/static/img/video_section_1.png'),
            num:129000,
            like:11000,
            time:'05:14',
            text:'小测试：JOJO中最适合你的替身是？',
            bk_img:require('@/static/img/video_section_move_1.jpg'),
            up_name:'啧鱼Zeyu',
            up_linkTo:'https://space.bilibili.com/450855167/',
            img_num:8
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1st4y1Y7WW',
            img:require('@/static/img/video_section_2.png'),
            num:59730000,
            like:743000,
            time:'03:01',
            text:' 课 堂 请 勿 对 对 子 2.0 ！！！',
            bk_img:require('@/static/img/video_section_move_2.jpg'),
            up_name:'三十六贱笑',
            up_linkTo:'https://space.bilibili.com/90361813/',
            img_num:33
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1t64y1f7hY',
            img:require('@/static/img/video_section_3.png'),
            num:148000,
            like:26000,
            time:'02:14',
            text:'大概只有大会员用户才能完全享受这个视频吧！用两分钟的纯净，还B站一份不虚荣的时间！',
            bk_img:require('@/static/img/video_section_move_3.jpg'),
            up_name:'粽子酱',
            up_linkTo:'https://space.bilibili.com/3834994/',
            img_num:27
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1Mv411t7ka',
            img:require('@/static/img/video_section_4.png'),
            num:340000,
            like:2298,
            time:'03:28',
            text:'"管他那么多，变就完了"',
            bk_img:require('@/static/img/video_section_move_4.jpg'),
            up_name:'茬子粥丶',
            up_linkTo:'https://space.bilibili.com/417208022/',
            img_num:35
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1ZA411s7Tx',
            img:require('@/static/img/flow_img2_4.jpg'),
            num:73000,
            like:6887,
            time:'02:19',
            text:'【仿原神/实时渲染】啊，这光！啊，这水！芭芭拉的Solo☆MV (?)【2D卡通渲染】',
            bk_img:require('@/static/img/video_section_move_5.jpg'),
            up_name:'NoiR_CCC',
            up_linkTo:'https://space.bilibili.com/10519465/',
            img_num:28
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1B54y1k7SV',
            img:require('@/static/img/video_section_5.png'),
            num:569000,
            like:46000,
            time:'08:25',
            text:'这可能就是副船长吧',
            bk_img:require('@/static/img/video_section_move_6.jpg'),
            up_name:'忘川邱水',
            up_linkTo:'https://space.bilibili.com/487205008/',
            img_num:94
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1Zp4y1q7rh',
            img:require('@/static/img/video_section_6.png'),
            num:34000,
            like:4323,
            time:'03:25',
            text: '【MMD/刻晴】圣诞节。。。。',
            bk_img:require('@/static/img/video_section_move_7.jpg'),
            up_name:'哲学小枭',
            up_linkTo:'https://space.bilibili.com/32510353/',
            img_num:41
          },
          {
            linkTo:'https://www.bilibili.com/video/BV1oD4y1X7mv',
            img:require('@/static/img/video_section_7.png'),
            num:149000,
            like:6831,
            time:'09:42',
            text:'银魂搞笑名称面第一期',
            bk_img:require('@/static/img/video_section_move_8.jpg'),
            up_name:'八嘎推番',
            up_linkTo:'https://space.bilibili.com/260974/',
            img_num:100
          }
        ]
      },
      expand_section:[
        {
          text:'搞笑',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/life/funny',
          section_data:[]
        },
        {
          text:'动物圈',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/life/animal',
          section_data:[]
        },
        {
          text:'美食',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/food',
          section_data:[]
        },
        {
          text:'单机游戏',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/game/stand_alone',
          section_data:[]
        },
        {
          text:'VLOG',
          num:'1230',
          linkTo:'https://www.bilibili.com/v/food',
          section_data:[]
        }
      ]
    }
  },
  actions:{
    preLoadFlowImg1(){
      return new Promise((resolve)=>{
        const arr = [
          require('@/static/img/flow_img_3.jpg'),
          require('@/static/img/flow_img_4.jpg'),
          require('@/static/img/flow_img_5.jpg'),
          require('@/static/img/flow_img_1.jpg')
        ];
        preLoad(arr).then(() => {
          const ptr_arr = this.flow_img_1_data;
          for(let i = 2;i < ptr_arr.length;i++){
            ptr_arr[i].img = arr[i-2];
          }
          resolve();
        });
      })
    },
    preLoadFlowImg2(){
      return new Promise((resolve)=>{
        const arr = [
          require('@/static/img/flow_img2_7.jpg'),
          require('@/static/img/flow_img2_8.jpg'),
          require('@/static/img/flow_img2_9.jpg'),
          require('@/static/img/flow_img2_10.jpg'),
          require('@/static/img/flow_img2_11.jpg'),
          require('@/static/img/flow_img2_12.jpg'),
          require('@/static/img/flow_img2_13.jpg'),
          require('@/static/img/flow_img2_14.jpg'),
          require('@/static/img/flow_img2_15.jpg'),
          require('@/static/img/flow_img2_16.jpg'),
          require('@/static/img/flow_img2_17.jpg'),
          require('@/static/img/flow_img2_18.jpg')
        ];
        preLoad(arr).then(() => {
          const ptr_arr = this.flow_img_2_data;
          for(let i = 6;i < ptr_arr.length;i++){
            ptr_arr[i].img = arr[i-6];
          }
          resolve();
        });
      })
    }
  }
});

export default useMainSection;